apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 3
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: alvarezrebeca/app
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: VERSION_INFO
          value: "VERSION_INFO_VALUE"
        - name: BUILD_DATE
          value: "BUILD_DATE_VALUE"
        ports:
        - containerPort: 8080