# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2
jobs:
  build-environment:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/capstone

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            pip install pylint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
            
  build-docker-image:
    docker:
      - image: circleci/aws-ecr@7.0.0
    working_directory: ~/capstone
    steps:
      - checkout
      - run: 
          name: build image
          command: |
            docker build -t app-${CIRCLE_WORKFLOW_ID:0:7}
      - run:
          name: tag image
          command: |
           docker tag app-${CIRCLE_WORKFLOW_ID:0:7}:latest 729501865919.dkr.ecr.eu-central-1.amazonaws.com/app:latest
      - run:
          name: push image
          command: |
           docker push app-${CIRCLE_WORKFLOW_ID:0:7}:latest
  
  workflows:
    default:
      jobs:
        - build-environment
        - build-docker-image:
            requires: [build-environment]